# Generated by Django 3.0.7 on 2020-07-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=1000)),
                ('singer_name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('song', models.FileField(upload_to='song')),
            ],
        ),
    ]
