# Generated by Django 3.0.7 on 2020-07-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20200711_1420'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_details',
        ),
    ]
